[package]
name = "splitter"
version = "0.1.0"
edition = "2021"

[dependencies]
heapless = "0.8.0"
log = "0.4"
simplelog = "0.12.2"
easy-error = "1.0.0"

[dev-dependencies]
time = { version = "0.3", features = ["macros"] }
